Feature/animation
mantle-labs/audit-portal pull request #2
Opened 2022-09-07 14:48 UTC by ben-nole

2022-09-09 18:58 UTC, nic758 requested changes

2022-09-09 18:58 UTC, nic758 commented on index.html
> +                <input type="text" class="form-control" placeholder="Enter pointer here" value="WAV3MwjsLVr64xVko3DXGKzfSoydb5bHjspRgt" id="pointer">
assure toi d'enlever la value avant de mergé la pr

2022-09-09 18:58 UTC, nic758 commented on scripts/script.js
> +    var txEl = $(`#i-${id}`)
txElem
hashElem

2022-09-09 18:58 UTC, nic758 commented on scripts/script.js
> +function showChainLogo(pointer){
showWavesLogo

2022-09-09 18:58 UTC, nic758 commented
Assure toi de comprendre le code du socket comme il faut.

2022-09-19 14:52 UTC, MantleFounder approved these changes
That's it tu t'enviens bon Benjo !

2022-09-19 14:52 UTC, MantleFounder commented on scripts/bdtp-client.js
> +async function processChunk(chunk){
Cool check cetait pas sorcier, juste bien breakdown les étapes !

2022-09-19 14:52 UTC, MantleFounder commented on scripts/script.js
> +async function fetchFromWaves(pointer) {
C'est sur qu'il va falloir refactor ca quand on va avoir plus de chaines mais c'est gucci pour l'instant

2022-09-19 19:00 UTC, ben-nole commented on scripts/script.js
> +async function fetchFromWaves(pointer) {
Oui ca c clair!

2022-09-20 14:40 UTC, nic758 requested changes
Destroy socket

2022-09-20 20:00 UTC, nic758 approved these changes

2022-09-20 20:00 UTC, merged